# pdx-chainstack
#
#       PDX blockchain hypercloud: chain stack 
#
# VERSION 0.1

FROM debian:9.5-slim 

LABEL maintainer="jz@pdx.ltd"

COPY pdx_home/bin/pdxc /pdx/bin/pdxc
COPY run-chain.sh /pdx/bin/run-chain.sh

ENTRYPOINT /pdx/bin/run-chain.sh
